# Linear Algebra 1
## Jan 11, 2024

## Vector Space
- Additive group (x+y, -x, 0): associativity, commutativity
- Scalar multiplication

## Speed of Computers
### How is it measured?

1. Floating-point Operations \[Flop/sec\]
- Intel CPU: 2.4 GHz * 8 * 2 (can do (a+b)+(c+d)) * 4 (two cycles like this) * 2 ~ 300 GFlop/sec (Giga Flop/sec) operation rate! --> "Double Precision"
- AMD GPU: 4000 GFlop/sec "Single Precision" ... for graphics, just Euclidean geometry (flat screen)
- Intel GPU: 400 GFlop/sec "Single Precision" ... uses much less energy, so appropriate for laptops

2. Memory Bandwidth \[Bytes/sec\] (Data transfer performance)
- System: 42 GByte/sec
- AMD GPU: 192 GByte/sec
    - 1 double = 8 bytes
    - 1 sec = 5 GReads
    - 1 sec = 300 GFlops
    - So Flop/Reads = 60 operations needed before processing another set of readings

## Speed of Algorithms: Big-O Notation
`O(f(n)) := {g(n): there exist C, n0 such that g(n) <= C f(n) for all n >= n0}`

        e.g. O(n^2): a*n^2 + b, with coefficient a and some quantity b that has order < n^2

## Cost of Operations
           Op    |    Flop    |    Memory Accesses
       ---------------------------------------------
          x + y  |    O(n)    |   O(2n+1)=O(n)      (n additions; 2 vectors with 1 vector result)
       ---------------------------------------------
    dot pd x*y   | O(2n)=O(n) |   O(2n+1)=O(n)      (n multiplications; 2 vectors with 1 scalar result)
       ---------------------------------------------
           Ax    |   O(n^2)   |   O(n^2+2n)=O(n^2)  (n multiplications n times; 1 matrix, 1 vector with 1 vector result)
       ---------------------------------------------
           AB    |   O(n^3)   |   O(3n^2)=O(n^2)    (n multiplications n^2 times; 2 matrices with 1 matrix result)
       ---------------------------------------------
          Ax=b   |   O(n^3)   |   O(n^2+3n)=O(n^2)  (n multiplications n^2 times; 2 matrices with 1 matrix result)

In [2]:
using BenchmarkTools

In [3]:
A = randn(2000,2000);
B = randn(2000,2000);
@benchmark A*B

BenchmarkTools.Trial: 15 samples with 1 evaluation.
 Range (min … max):  318.139 ms … 360.418 ms  ┊ GC (min … max): 0.00% … 2.70%
 Time  (median):     336.030 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   335.520 ms ±  11.637 ms  ┊ GC (mean ± σ):  1.06% ± 1.80%

  ▁    ▁  ▁    ▁ ▁▁ ▁      █  ▁ ▁       ▁   ▁   ▁             ▁  
  █▁▁▁▁█▁▁█▁▁▁▁█▁██▁█▁▁▁▁▁▁█▁▁█▁█▁▁▁▁▁▁▁█▁▁▁█▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  318 ms           Histogram: frequency by time          360 ms <

 Memory estimate: 30.52 MiB, allocs estimate: 2.

In [4]:
(2*2000^3)/300.0e9 # Cost of matrix multiplication (Flop operations)

0.05333333333333334

In [5]:
@benchmark A+B

BenchmarkTools.Trial: 248 samples with 1 evaluation.
 Range (min … max):  13.604 ms … 131.042 ms  ┊ GC (min … max):  0.00% …  0.00%
 Time  (median):     15.804 ms               ┊ GC (median):     0.00%
 Time  (mean ± σ):   20.191 ms ±   9.977 ms  ┊ GC (mean ± σ):  15.66% ± 17.04%

  ▄▆█▅▄             ▁▃▄▄ ▁▁                                     
  ██████▄▇▆▁▆▁▄▁▄▆▁▆███████▄▁▁▆▆▄▄▆▄▁▄▁▁▁▁▁▁▁▄▁▁▁▁▁▄▁▆▁▁▁▁▄▁▁▄ ▆
  13.6 ms       Histogram: log(frequency) by time      46.8 ms <

 Memory estimate: 30.52 MiB, allocs estimate: 2.

Indeed much faster than matrix multiplication!!

In [6]:
(2000^2)/300.0e9 # Cost of matrix addition (Flop operations)

1.3333333333333333e-5

In [7]:
(3* 2000^2)/5.0e9 # Cost of matrix addition (Memory access/use)

0.0024

## Linear Algebra Algorithms in Julia
Julia is built *for* linear algebra!

In [8]:
using LinearAlgebra #built-in package

In [9]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [10]:
zeros(3,3)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [11]:
randn(3) # random 3-vector

3-element Vector{Float64}:
  0.4755377857225412
 -0.6423772903650239
 -0.915090110065141

In [12]:
randn(3,3) # random 3x3 matrix

3×3 Matrix{Float64}:
 -0.179009  -1.11682    2.38621
 -1.33089   -1.13028   -0.0930987
  0.82508    0.168618   0.14634

In [13]:
rand(3) # random scalar between 0 and 1

3-element Vector{Float64}:
 0.08888159603704948
 0.9748402913119574
 0.9427031507203351

In [14]:
A = randn(3,3)
x = randn(3)

size(A)

(3, 3)

In [15]:
size(x)

(3,)

In [16]:
typeof(A)

Matrix{Float64} (alias for Array{Float64, 2})

In [17]:
typeof(x)

Vector{Float64} (alias for Array{Float64, 1})

In [18]:
A' # adjoint

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 2.01635   1.18712   0.982973
 2.03972  -0.526106  0.0813878
 1.35059  -1.04266   0.41488

In [19]:
typeof(A') # for adjoint/transpose, Julia just accesses the original matirx in a different way, without using new memory

Adjoint{Float64, Matrix{Float64}}

In [20]:
Symmetric(A) # symmetrizes matrix (using the upper triangle)

3×3 Symmetric{Float64, Matrix{Float64}}:
 2.01635   2.03972    1.35059
 2.03972  -0.526106  -1.04266
 1.35059  -1.04266    0.41488

In [21]:
A \ x

3-element Vector{Float64}:
 -0.5402093589024277
  1.5248777787414125
 -1.0177485578210315

In [22]:
det(A)

-2.535172682723199

In [23]:
inv(A) # inverse

3×3 Matrix{Float64}:
  0.0526241   0.290441   0.558615
  0.598547    0.193693  -1.46171
 -0.2421     -0.726136   1.37356

In [24]:
# want to solve A*x=b
b = randn(3)
inv(A)*b # don't do this!!! inversion can take FOREVER!

3-element Vector{Float64}:
  1.1279743969176614
 -2.929330974599164
  2.167615581938823

In [25]:
eigen(A) # eigen decomposition

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -1.613595033344347
  0.5247689549308608
  2.993952208924382
vectors:
3×3 Matrix{Float64}:
 -0.540272   0.137718  -0.912847
  0.80964   -0.61487   -0.2029
  0.229324   0.776511  -0.35432

In [26]:
svd(A) # singular value decomposition

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 -0.962595    0.0820016  -0.258236
 -0.0127858  -0.965787   -0.259021
 -0.270642   -0.24603     0.930711
singular values:
3-element Vector{Float64}:
 3.2879356610728165
 1.7195305033918717
 0.4484090318994326
Vt factor:
3×3 Matrix{Float64}:
 -0.675847  -0.601813  -0.425501
 -0.711241   0.381117   0.590666
  0.193304  -0.701834   0.685611

But this can be slow, especially if we want only some of the eigenvalues/vectors!

In [27]:
using Arpack

In [28]:
eigs(A)

┌ Warning: Adjusting nev from 6 to 1
└ @ Arpack C:\Users\hpark1\.julia\packages\Arpack\FCvNd\src\Arpack.jl:92


(ComplexF64[2.993952208924383 + 0.0im], ComplexF64[-0.9128465405462922 + 0.0im; -0.20290011833895774 + 0.0im; -0.35432010300109074 + 0.0im;;], 1, 1, 3, [0.0, 0.0, 0.0])

In [29]:
svds(A)

LoadError: ArgumentError: number of singular values (nsv) must be < 3, got 6

REMARK: For SVD, Julia *pre*allocates memory, first expecting the size of the result.