# Linear Algebra 2
## Jan 15, 2024 ~ Jan 16, 2024

# Benchmarking

In [4]:
@benchmark ys = sin.(xs)

BenchmarkTools.Trial: 10000 samples with 5 evaluations.
 Range (min … max):   5.640 μs …  21.884 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):      5.760 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   22.842 μs ± 419.462 μs  ┊ GC (mean ± σ):  5.13% ± 1.72%

  █▃▄▄▄▂                                                       ▁
  ███████▇▇▇▇▆▅▅▃▄▄▃▃▃▁▄▁▅▆▆▆▆▆▇▇▇▇██▇▇▇▇▆▆▆▅▅▆▆▄▅▆▅▅▃▄▅▄▅▄▅▅▄ █
  5.64 μs       Histogram: log(frequency) by time      58.4 μs <

 Memory estimate: 2.69 KiB, allocs estimate: 2.

In [2]:
xs = 0:0.01:pi
@time ys = sin.(xs)

  0.333758 seconds (182.06 k allocations: 11.767 MiB, 35.84% gc time, 99.96% compilation time)


315-element Vector{Float64}:
 0.0
 0.009999833334166664
 0.01999866669333308
 0.02999550020249566
 0.03998933418663416
 0.04997916927067833
 0.059964006479444595
 0.06994284733753277
 0.0799146939691727
 0.08987854919801104
 0.09983341664682815
 0.10977830083717481
 0.11971220728891936
 ⋮
 0.11136118868664958
 0.10141798631660187
 0.09146464223243675
 0.08150215176026912
 0.07153151114084326
 0.06155371742991315
 0.05156976839853464
 0.04158066243329049
 0.031587398436453896
 0.02159097572609596
 0.011592393936158275
 0.0015926529164868282

In [3]:
using BenchmarkTools

# Sparse Matrices

In [1]:
using LinearAlgebra
using SparseArrays

In [10]:
A=sprand(10, 10, 0.2) # sparse random matrix

10×10 SparseMatrixCSC{Float64, Int64} with 11 stored entries:
  ⋅    ⋅         ⋅         ⋅         …  0.33567    ⋅         ⋅         ⋅ 
  ⋅    ⋅         ⋅         ⋅             ⋅         ⋅         ⋅         ⋅ 
  ⋅    ⋅         ⋅         ⋅             ⋅         ⋅         ⋅         ⋅ 
  ⋅   0.172441   ⋅         ⋅             ⋅         ⋅        0.546291   ⋅ 
  ⋅    ⋅         ⋅         ⋅             ⋅         ⋅         ⋅         ⋅ 
  ⋅    ⋅        0.446846   ⋅         …  0.241859  0.738364   ⋅         ⋅ 
  ⋅    ⋅         ⋅         ⋅            0.214545   ⋅         ⋅         ⋅ 
  ⋅    ⋅         ⋅         ⋅             ⋅         ⋅        0.754534   ⋅ 
  ⋅    ⋅         ⋅         ⋅             ⋅         ⋅         ⋅         ⋅ 
  ⋅    ⋅         ⋅        0.0936715      ⋅         ⋅         ⋅         ⋅ 

## Efficiency
                  |       Full        |      Sparse
    -----------------------------------------------------
    memory  A     |       O(n^2)      |      O(n\*p)
    -----------------------------------------------------
    cost    Ax    |    O(n\*n=n&2)    |      O(n\*p)
    -----------------------------------------------------
           Ax=b   |       O(n^3)      |     ? (the inverse of sparse matrix is usually FULL matrix! Can show by Gaussian elimination)

In [12]:
inv(A) # see, it doens't like to calculate

LoadError: The inverse of a sparse matrix can often be dense and can cause the computer to run out of memory. If you are sure you have enough memory, please either convert your matrix to a dense matrix, e.g. by calling `Matrix` or if `A` can be factorized, use `\` on the dense identity matrix, e.g. `A \ Matrix{eltype(A)}(I, size(A)...)` restrictions of `\` on sparse lhs applies. Alternatively, `A\b` is generally preferable to `inv(A)*b`

In [14]:
pinv(Matrix(A)) # why does this work?

10×10 Matrix{Float64}:
  0.0        0.0           0.0          …   0.0      0.0   0.0
  0.0        6.6224e-16    1.65857e-15     -4.19861  0.0  -1.36907e-15
 -0.146277   1.04275e-30  -6.24055e-32      0.0      0.0   2.41492e-15
  0.0        4.60123e-15  -2.7537e-16       0.0      0.0  10.6756
  0.0        9.08865e-16  -5.43929e-17      0.0      0.0  -2.06914e-16
 -0.296038  -4.99088e-31   2.98689e-32  …   0.0      0.0  -1.08348e-15
  2.11507    0.0           0.0              0.0      0.0  -1.63902e-33
 -0.241707  -1.97804e-32   1.1838e-33       0.0      0.0  -1.34447e-16
  0.0       -6.84903e-17  -1.00008e-16      1.32532  0.0   3.11636e-18
  0.0        0.0           0.0              0.0      0.0   0.0

In [15]:
spzeros(10, 10)

10×10 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 

In [16]:
Diagonal(1:10)

10×10 Diagonal{Int64, UnitRange{Int64}}:
 1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  2  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  3  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  4  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  5  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  6  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  7  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  8  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  9   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  10

In [17]:
sparse(Diagonal(1:10))

10×10 SparseMatrixCSC{Int64, Int64} with 10 stored entries:
 1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  2  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  3  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  4  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  5  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  6  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  7  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  8  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  9   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  10

In [20]:
Bidiagonal(1:10, 1:9, :U) # upper bidiagonal matrix

10×10 Bidiagonal{Int64, UnitRange{Int64}}:
 1  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  2  2  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  3  3  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  4  4  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  5  5  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  6  6  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  7  7  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  8  8   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  9   9
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  10

In [22]:
Tridiagonal(2:10, 1:10, 5:13)  #lower, main, upper diagonal

10×10 Tridiagonal{Int64, UnitRange{Int64}}:
 1  5  ⋅  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅
 2  2  6  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅
 ⋅  3  3  7  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅
 ⋅  ⋅  4  4  8  ⋅   ⋅   ⋅   ⋅   ⋅
 ⋅  ⋅  ⋅  5  5  9   ⋅   ⋅   ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  6  6  10   ⋅   ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  7   7  11   ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   8   8  12   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅   9   9  13
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅   ⋅  10  10

In [30]:
sprandn(100, 100, 0.2) # sparse random matrix with (row, column, density). Now, no longer shows numbers but patterns!

100×100 SparseMatrixCSC{Float64, Int64} with 2004 stored entries:
⎡⠀⠀⢰⡟⠌⠶⣠⡥⠨⠂⠀⠴⠣⡏⠡⡄⠠⠕⠔⠄⠠⠀⢐⠠⠮⠃⢨⢈⣾⠁⠰⠌⡰⢀⠶⠡⠰⢢⢢⢄⎤
⎢⠮⠍⢈⠀⠤⡧⠤⠅⣂⡢⠠⠁⠀⡤⠄⡌⠐⢁⠄⠅⠨⠠⠱⢨⣤⠄⢾⠪⠴⢀⠠⠤⢐⢷⠢⠐⠨⢀⢠⠀⎥
⎢⢤⠤⠴⠖⡀⠧⠇⠄⠌⠥⢣⡅⡡⢦⡥⠠⠰⡔⠄⣔⠱⠁⡰⠈⢼⡘⠰⢆⠈⠠⠑⠡⢠⠡⢲⠀⡍⡈⠀⢀⎥
⎢⡀⠅⡂⠕⠀⣱⡆⠗⠒⠄⣃⡃⠔⠄⣈⠓⠁⠔⠀⢕⠀⠁⢧⢅⡆⡢⡄⠠⠆⠠⠅⢂⠐⢇⠨⡓⠄⠬⠠⡄⎥
⎢⠡⠥⠒⠏⠤⠂⠪⡨⢄⠼⠘⡨⠀⠄⡤⠀⠍⠢⠠⠄⠹⢂⢀⠀⠈⡀⢮⠁⠱⠐⢬⠄⠄⡐⢨⠠⠣⠔⠨⡤⎥
⎢⠀⠄⠘⠐⠢⡌⡄⠆⡤⠖⠁⢆⠀⠰⠵⠊⠀⡥⠀⠼⠰⠀⠨⡔⣀⠔⠰⠩⠐⠤⠪⠤⠴⢢⠢⠔⠤⡀⠜⢑⎥
⎢⠠⣆⠛⠆⠢⠮⠐⡤⡁⢰⠐⣂⠀⠥⠰⠮⠈⡤⠸⠀⠠⡡⡰⠃⢧⠈⠘⡀⢬⡈⠘⠌⠭⠀⠨⠀⢎⠰⢔⢢⎥
⎢⣨⢢⠦⠇⠂⠅⠉⡌⠂⡴⡢⡌⠈⡰⠠⠁⡔⡃⢙⢇⠈⠀⠇⠰⡸⢔⢂⡁⡸⠀⡊⠌⠈⠴⢒⠀⠌⡠⠄⠔⎥
⎢⠕⡌⠈⠀⠰⡿⠄⠂⣄⠁⠤⠂⠂⠂⡈⡣⡀⠄⠀⠡⡨⠀⠐⢇⣹⠎⠍⠤⢙⠀⡰⢎⠴⢀⠠⠀⣠⢀⠰⠄⎥
⎢⡴⡂⠅⡀⠄⠁⡜⠜⠬⠒⠡⡄⠊⠢⠀⣅⠔⡈⢾⡗⢦⠘⠀⠀⢘⠉⢒⢀⢌⢄⢶⠀⠈⣐⠴⢙⠄⠠⠄⠠⎥
⎢⠲⣖⡄⢓⠒⠄⠐⠓⠈⠶⠠⡂⡄⡀⠀⢁⠀⠐⠅⡖⣐⠂⠘⠤⠊⢋⢒⠀⢜⡐⢗⡘⠰⢘⠸⠁⠺⠐⡂⢐⎥
⎢⠐⠋⠐⡨⠐⠗⠄⠃⡘⠒⠺⠖⠄⠲⡁⠂⠠⠔⠀⠪⠰⠠⠘⡃⢐⡑⠊⠀⢺⢆⢹⣖⣰⡐⠯⠉⣂⡂⠲⠀⎥
⎢⢀⡆⡐⢳⡐⡀⠀⠀⢮⢑⣠⢠⠀⠦⢂⣓⠀⠦⡀⡓⠂⠐⠚⠐⡘⠆⡒⡧⠐⠠⢞⢁⢘⠂⠔⢈⠬⢉⠚⠀⎥
⎢⠠⢒⢐⢄⡂⡓⡂⠈⠐⡞⢍⡐⢰⠅⠈⠁⣂⠨⠐⢇⠙⠨⢚⠀⢒⠄⢂⡐⠐⣦⢠⢌⢂⡚⢎⢖⡐⣐⠨⢒⎥
⎢⢀⡓⠬⠂⢢⢂⢀⡋⠢⠉⠨⡃⠖⠆⣩⠁⡠⣀⠂⡰⣃⢃⠸⡢⠂⣐⠀⠐⢢⠬⢐⡄⠐⠒⠂⢂⠒⠑⢃⠂⎥
⎢⠩⠕⡊⠂⠐⣢⡐⠇⠐⠔⠢⡄⠀⠂⡐⢃⠆⡊⠑⠂⢒⠓⠜⢓⠁⡰⢒⢐⠊⠂⠴⡄⢒⠙⠰⠁⠹⡒⠉⢖⎥
⎢⠒⡱⡸⡼⡐⠀⠖⠋⠐⣶⢆⠂⠈⠀⠂⡗⠀⠖⠊⡀⠘⢘⠒⠸⠿⠓⠑⠞⠥⣋⢍⠠⡕⠀⠂⠐⢜⠤⠀⠐⎥
⎢⠀⡂⠈⡀⡅⢷⠴⠣⢂⠋⡹⢰⠱⣄⡣⡓⠆⠢⠂⠂⠒⠂⢴⢐⠕⢁⠆⠂⠚⠸⠐⣀⢠⠂⠀⠀⢚⠀⢠⠤⎥
⎢⠘⡀⢂⠓⠢⠓⠰⠅⠚⠖⠣⣔⢘⡃⡀⠁⠒⠂⠥⡞⢐⢈⢛⠅⡃⠀⠂⠂⣠⢴⢀⠅⢑⠒⣠⢆⠳⠨⡢⡐⎥
⎣⠈⢀⠀⠩⠰⠑⠁⣀⡐⠠⡁⠀⠐⠙⢀⠃⡰⢄⠰⡄⠑⠢⢘⠁⢕⡁⡜⡀⠜⠆⠹⠑⢂⡈⢋⠄⡚⡲⠚⢑⎦

## Symmetric, Positive-Definite (SPD) Matrix
- Symmetric: allows inverse
- Positive-definite: gives valid positive eigenvalues

$A x = b$

$x^*$ true solution

$x$ approximate solution

$e:=x-x^*$ error

$r:=b-Ax$ residual

We define
$$ G:=\frac{1}{2} x^TAx-b^Tx $$
$$ \nabla G=Ax-b \equiv -r$$



### Gradient/Steepest Descent Algorithm
- Used to study random neural networks
- IBM explains: "Gradient descent is an optimization algorithm which is commonly used to train machine learning models and neural networks. Training data helps these models learn over time, and the cost function within gradient descent specifically acts as a barometer, gauging its accuracy with each iteration of parameter updates."

#### Julia Implementation
        A = randn(10,10)
        A = A + A'
        A = A*A (matrix multiplication)

In [2]:
function gd(A, b, n)
    """Julia implementation of gradient/steepest descent"""
    x = zero(b)
    for i in 1:n
        r = b - A*x
        alpha = - (transpose(x)*A*r - transpose(b)*r)/(transpose(r)*A*r)
        x = x + alpha*r
    end
    return x
end

gd (generic function with 1 method)

In [4]:
function gradient_descent(A, b, n)
    """Solution: Julia implementation of gradient/steepest descent"""
    x0 = A \ b
    x = zero(b)
    for i in 1:n
        r = b - A*x
        println("iter $i    |e|=$(norm(x-x0))    |r|=$(norm(r))")
        # x1 = x + alpha*r
        # min!(|b - A*x1|^2)
        # min!(|r - alpha*A*r|^2)
        # solve!((r-alpha*A*r)*(A*r))
        s = A * r
        alpha = (r' * s) / (s' * s)
        x += alpha * r
    end
    return x
end

gradient_descent (generic function with 1 method)

In [6]:
b = randn(10)
A = sprand(10, 10, 0.2)
x = gd(Matrix(A),b, 20)

10-element Vector{Float64}:
   7.470671668192373
 -22.55758818934296
  -3.589330351663579
   5.3287295889677395
   5.3560942256599215
   6.653928897100298
   7.088885615124942
  -0.6489164957794264
  -2.703151465785931
  -8.37498752119924

... But Gradient Descent can "overshoot" in the direction too much. Can't finish good approximation in two steps!
So we use "Conjugate Gradient Descent"!

## Conjugate Gradient Descent
- A combination of the original Gradient Descent Method and Newton's Method.
- Chooses a new direction that is ORTHOGONAL to all the previous directions (since the error is orthogonal, move orthogonal to the error direction)! The direction taken at each step is orthogonal to the directions at all previous steps---"orthogonal" in "operator-A sense".

CMU lecture: https://www.cs.cmu.edu/~pradeepr/convexopt/Lecture_Slides/conjugate_direction_methods.pdf

In [7]:
function conjugate_gradients(A, b, n)
    x0 = A \ b
    x = zero(b)
    r = b - A*x
    s = r
    for i in 1:n
        println("iter $i    |e|=$(norm(x-x0))    |r|=$(norm(r))")
        alpha = (r' * r) / (s' * A * s)
        x1 = x + alpha*s
        #r1 = r - alpha*A*s
        r1 = r - A*x1
        beta1 = (r1' * r1) / (r' * r)
        s1 = r1 + beta1*s
        x = x1
        r = r1
        s = s1
    end
    return x
end

conjugate_gradients (generic function with 1 method)

In [9]:
x = conjugate_gradients(A, b, 20)
norm(x - x0), norm(b - A*x)

LoadError: SingularException(0)

Much faster, since the path to the solution is zig-zag!